# Generated by Django 5.0.7 on 2024-08-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='ubication',
            new_name='room_number',
        ),
    ]
