# Generated by Django 5.0.7 on 2024-08-05 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_ubication_space_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='state',
        ),
    ]
