# Generated by Django 5.0.7 on 2024-08-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_reservation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
