# Generated by Django 5.0.7 on 2024-08-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_space_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='state',
            new_name='available',
        ),
    ]
