# Generated by Django 5.0.7 on 2024-08-10 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space_Type',
            fields=[
                ('space_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Types',
        ),
        migrations.AlterField(
            model_name='space',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.space_type'),
        ),
    ]
