# Generated by Django 5.0.7 on 2024-08-08 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_state_space_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='username',
        ),
    ]
