# Generated by Django 5.0.7 on 2024-08-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_space_type_delete_types_alter_space_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Space_Type',
        ),
    ]
