# Generated by Django 5.0.7 on 2024-08-08 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_full_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='full_name',
        ),
    ]
