# Generated by Django 5.0.7 on 2024-08-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_space_type_delete_space_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space_Type',
            fields=[
                ('space_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
    ]
