# Generated by Django 5.0.7 on 2024-08-10 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_space_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Space_Type',
            new_name='SpaceType',
        ),
    ]
