# Generated by Django 5.0.7 on 2024-08-10 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_space_type_spacetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.spacetype'),
        ),
    ]
