# Generated by Django 5.0.7 on 2024-08-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_type_spacetype_type_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spacetype',
            old_name='space_type_id',
            new_name='type_id',
        ),
    ]
