# Generated by Django 5.0.7 on 2024-10-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_type_resource_name_spacexresource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='name',
            new_name='type',
        ),
        migrations.DeleteModel(
            name='SpaceXResource',
        ),
    ]
