# Generated by Django 5.0.7 on 2024-10-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_type_resource_name_spacexresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='available_resources',
        ),
        migrations.AddField(
            model_name='space',
            name='resources',
            field=models.ManyToManyField(related_name='spaces', through='core.SpaceXResource', to='core.resource'),
        ),
    ]
