# Generated by Django 5.0.7 on 2024-10-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_space_available_resources_space_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Close', 'Close'), ('Available', 'Available'), ('Cancel', 'Cancel')], default='Available', max_length=10),
        ),
    ]
