# Generated by Django 5.0.7 on 2024-11-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_notifications_is_read_alter_notifications_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacexresource',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
